### ISSUE TITLE
doesn't work with any Tailwind UI component that requires javascript

### ISSUE THREAD

**Issue by skaeneman** [ntamvl/Rails7WithReactTailwindCSSBootstrapExample#1]
When I try to use a Tailwind UI component it will not render any actions for dropdowns, navbar, etc... for example, if I paste the first option for a dropdown into one of the views it will not render correctly.  https://tailwindui.com/components/application-ui/elements/dropdowns

**Comment by ntamvl** [comment]
@skaeneman Sorry for the late reply, I've been busy with work lately and forgot to check this repo.
I use tailwind prefix `tw-` for this example, I have created a simple tool to generate tailwind prefix code http://tailwind-prefix-generator.ntam.me/ :) 
I also create a example page for dropdown: https://github.com/ntamvl/Rails7WithReactTailwindCSSBootstrapExample/blob/main/app/views/pages/demo.html.erb
